### ISSUE TITLE
Branding, typeface

### ISSUE THREAD

**Issue by notshi** [bradford-coderdojo/bradford-coderdojo.github.io#3]
Wasn't sure what the details are for this part of the org so I did some stuffs - are these ok?

- Added a [temporary logo](https://github.com/bradford-coderdojo/bradford-coderdojo.github.io/blob/master/assets/website/logo_640x640.svg) to play with - mostly to fit the ratio of the organization logo.

- I replaced the numbers with the Bradford postcode. Typeface used is [Dosis](https://fonts.google.com/specimen/Dosis?selection.family=Dosis).

**Comment by jonnymuir** [comment]
I like it
